### ISSUE TITLE
module 'fzy' not found

### ISSUE THREAD

**Issue by bryceyang** [camspiers/snap#14]
### nvim version
```
NVIM v0.5.0-dev+1354-ga282a177d
Build type: Release
LuaJIT 2.1.0-beta3
```
### package manager
packer: 
```
use { 'camspiers/snap', rocks = {'fzy'}}
```

### config
copy from readme: https://gist.github.com/camspiers/686395ab3bda4a0d00684d72acc24c23

### issue
after packer compile, packer install  and restart nvim, I got this:
```
E5113: Error while calling lua chunk: ...ite/pack/packer/start/snap/lua/snap/consumer/fzy/all.lua:3: module 'fzy' not found:
        no field package.preload['fzy']
        no file './fzy.lua'
        no file '/home/xxx/github/neovim/.deps/usr/share/luajit-2.1.0-beta3/fzy.lua'
        no file '/usr/local/share/lua/5.1/fzy.lua'
        no file '/usr/local/share/lua/5.1/fzy/init.lua'
        no file '/home/xxx/github/neovim/.deps/usr/share/lua/5.1/fzy.lua'
        no file '/home/xxx/github/neovim/.deps/usr/share/lua/5.1/fzy/init.lua'
        no file './fzy.so'
        no file '/usr/local/lib/lua/5.1/fzy.so'
        no file '/home/xxx/github/neovim/.deps/usr/lib/lua/5.1/fzy.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

I am not familiar with lua stuff.  intuitively, I feel that this is an env-related problem, but I don't know how to fix it. Please help.

**Comment by camspiers** [comment]
It might be this issue:

https://github.com/wbthomason/packer.nvim/issues/180

**Comment by mactep** [comment]
I don't know exactly where to report this, but I'm getting the same error, even when using the solution provided on [wbthomason/packer.nvim#180](https://github.com/wbthomason/packer.nvim/issues/180). Looking at the error message I can see that it's not searching locally for fzy. I was able to fix it either by running `sudo luarocks install fzy` or copying those fzy files to the same directory as `all.lua` file. Am I missing something here? Should it be able to look fook user specific local folder, so instead of `/usr/local/*` it would be `~/.local/*`?
